language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6
matrix:
  allow_failures:
    - rvm: jruby-head
  only:
    - rvm: jruby-19mode
      jdk: openjdk7
    - rvm: jruby-19mode
      jdk: oraclejdk7
    - rvm: jruby-19mode
      jdk: openjdk6
branches:
  only:
    - master
before_install:
  only:
    - rvm: 2.0.0
      - gem update --system
      - gem --version
notifications:
  email:
    recipients:
      - mikael@zoolutions.se
matrix:
  allow_failures:
    - rvm: jruby-19mode